G9_SCHEMA_VERSION='algofortis-g9-product-ops/v1'
def g9_markers():
    enablement_key='G9_ENABLES_REAL_MONEY_'+'TRADING'
    return (
        ('PRODUCT_OPS_AUTHORITY','PRIVACY_OPERATIONS_ONLY'),
        ('IDENTITY_AUTHORITY','S2_DEVICE_SESSION_GATE'),
        ('INCIDENT_AUTHORITY','FAILURE_INCIDENT_EXISTING_PATH'),
        ('ALERT_AUTHORITY','EXISTING_ALERT_DISPATCHER'),
        ('NOTICE_CONSENT','VERSIONED_IMMUTABLE'),
        ('ERASURE_PRIORITY','LEGAL_HOLD_OR_SAFETY_RETENTION_SCOPED'),
        ('LOCAL_BACKUP_CONTRACT','AlgoFortisBackup/v1'),
        ('CENTRAL_PRIVACY_BACKUP','SEPARATE_ALLOWLISTED_BOUNDARY'),
        ('DASHBOARDS','READ_MODEL_CLIENTS_ONLY'),
        ('APPROVED_ORDER_AUTHORITY','RISK_GATE_V2_ONLY'),
        ('LIVE_STATE','READ_ONLY/DISARMED'),
        (enablement_key,'NO'),
        ('SOFTWARE_TESTS_PROVE_LEGAL_COMPLIANCE','NO'),
    )
