/**
 * SentinelX Owner Dashboard — Regulatory Reports Registry & D16 Immutable Audit Oversight
 */
import type { Truth, ReportItem } from "../../shared/data/sharedTypes";
import { STORAGE_KEYS, prototypeFixtureStorage, safeGetJson, safeSetJson } from "../../shared/data/storage";

const localStorage = prototypeFixtureStorage;

export type ReportCategoryType =
  | "BACKTEST_SUMMARY"
  | "PAPER_PERFORMANCE"
  | "PORTFOLIO_EXPOSURE"
  | "EXECUTION_QUALITY"
  | "STRATEGY_CONFORMANCE"
  | "RISK_REJECTIONS"
  | "PAPER_RECONCILIATION"
  | "DATASET_PROVENANCE"
  | "ACCESS_ENTITLEMENT"
  | "SYSTEM_AUDIT_LOG";

export type ReportGenerationState = "READY" | "GENERATING" | "REQUESTED" | "FAILED";

export interface OwnerReportRow {
  id: string;
  reportId: string;
  reportType: ReportCategoryType;
  title: string;
  scope: string;
  environment: "BACKTEST" | "PAPER" | "LIVE / SAMPLE" | "SYSTEM";
  strategyId?: string;
  accountId?: string;
  runId?: string;
  sessionId?: string;
  period: string;
  generatedAt: string;
  status: ReportGenerationState;
  format: "JSON / SUMMARY" | "CSV / LEDGER" | "EVIDENCE PACK";
  evidenceRef: string;
  metrics: Record<string, string | number>;
  summary: string;
  provenance: string;
}

export interface OwnerAuditRow {
  id: string;
  eventId: string;
  timestamp: string;
  actor: string;
  actorType: "OWNER" | "SYSTEM" | "USER" | "ENGINE";
  eventFamily: string; // D16 approved family (E1-E22)
  eventType: string; // Granular event type
  severity: "INFO" | "WARNING" | "CRITICAL";
  status: "SUCCESS" | "REJECTED" | "FAILED" | "CANCELLED" | "EXPIRED";
  entity: string;
  strategyId?: string;
  accountId?: string;
  orderId?: string;
  sessionId?: string;
  details: string;
  evidenceRef: string;
  reason?: string;
}

export const INITIAL_OWNER_REPORTS: OwnerReportRow[] = [];

export const INITIAL_OWNER_AUDIT_EVENTS: OwnerAuditRow[] = [];

const OWNER_REPORTS_KEY = STORAGE_KEYS.OWNER_REPORTS;
const OWNER_AUDIT_KEY = STORAGE_KEYS.OWNER_AUDIT_EVENTS;

export function getStoredOwnerReports(): OwnerReportRow[] {
  try {
    const raw = localStorage.getItem(OWNER_REPORTS_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

export function saveOwnerReports(reports: OwnerReportRow[]): void {
  try {
    localStorage.setItem(OWNER_REPORTS_KEY, JSON.stringify(reports));
  } catch (err) {
    console.error("Failed to save reports", err);
  }
}

export function requestReportGenerationSimulated(
  reportType: ReportCategoryType,
  scope: string,
  environment: "BACKTEST" | "PAPER" | "LIVE / SAMPLE" | "SYSTEM",
  period: string,
  actor: string = "OWNER-001"
): { success: boolean; message: string; report?: OwnerReportRow } {
  const current = getStoredOwnerReports();
  const nowStr = new Date().toISOString().replace("T", " ").substring(0, 19) + " UTC";
  const newReportId = `REP-${Date.now().toString().slice(-8)}`;

  const newReport: OwnerReportRow = {
    id: `rep-${Date.now()}`,
    reportId: newReportId,
    reportType,
    title: `${reportType.replace(/_/g, " ")} · ${scope}`,
    scope,
    environment,
    period,
    generatedAt: nowStr,
    status: "READY",
    format: "EVIDENCE PACK",
    evidenceRef: `sim-ev-${Date.now().toString(16)}`,
    metrics: {
      "Status": "READY (SIMULATED)",
      "Generation Mode": "Interactive Prototype Snapshot",
      "Evaluated Scope": scope,
      "Evidence Quality": "EVIDENCE ACCEPTED",
    },
    summary: `Simulated report generated by ${actor} for ${scope} covering period ${period}. (DEV PREVIEW / SAMPLE)`,
    provenance: `Simulated Report Generator Subsystem · Requested by ${actor}`,
  };

  current.unshift(newReport);
  saveOwnerReports(current);

  return {
    success: true,
    message: `SIMULATED REPORT REQUEST completed for "${newReport.title}". (DEV PREVIEW / SAMPLE)`,
    report: newReport,
  };
}

// PROTOTYPE FIXTURE STORE:
// The functions below provide local browser prototype fixtures modeling the D16 schema.
// They are NOT authoritative audit mutation APIs and do not provide backend durability.
export function getStoredOwnerAuditEvents(): OwnerAuditRow[] {
  try {
    const raw = localStorage.getItem(OWNER_AUDIT_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

export function saveOwnerAuditEvents(events: OwnerAuditRow[]): void {
  try {
    localStorage.setItem(OWNER_AUDIT_KEY, JSON.stringify(events));
  } catch (err) {
    console.error("Failed to save audit events prototype state", err);
  }
}
